[package]
name = "termal"
version = "1.2.2"
edition = "2021"
license-file = "LICENSE"
description = "Rust library for fancy colored cli using ansi codes"
homepage = "https://github.com/BonnyAD9/termal"
repository = "https://github.com/BonnyAD9/termal"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "termal_core",
    "termal_proc"
]

[dependencies]
termal_core = { path = "termal_core", version = "1.1.0" }
termal_proc = { path = "termal_proc", version = "1.1.0" }
